
// localhost
### Create Realtor
POST http://localhost:10000/realtors HTTP/1.1
Content-Type: application/json

{
  "firstName": "Blake",
  "lastName": "King",
  "email": "BlakeKing@fakemail.com",
  "phone": "555-555-5555",
  "city": "New York",
  "state": "NY",
  "zip": "10001"
}

### Edit Realtor
PUT http://localhost:10000/realtors HTTP/1.1 
content-type: application/json

{
  "firstName": "Blake",
  "lastName": "King",
  "email": "BlakeKing@fakemail.com",
  "phone": "111-111-1111",
  "city": "New York",
  "state": "NY",
  "zip": "10001"

}
### Delete Realtor
DELETE http://localhost:10000/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Get Realtor
GET http://localhost:10000/realtors HTTP/1.1

### Get Realtor by id

GET http://localhost:10000/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Get api documentation
GET http://localhost:10000/api-docs HTTP/1.1


### Create Home
POST http://localhost:10000/homes HTTP/1.1
Content-Type: application/json

{
     "sellerFirstName" : "Blake",
      "sellerLastName" : "King",
      "address" : "123 Main St",
      "realtorName": "Blake King",
      "realtorPhone": "555-555-5555",
}

### Edit Home
PUT http://localhost:10000/homes HTTP/1.1 
content-type: application/json

{
     "sellerFirstName" : "Joe",
      "sellerLastName" : "King",
      "address" : "123 Main St",
      "realtorName": "Blake King",
      "realtorPhone": "555-555-5555",

}
### Delete Home
DELETE http://localhost:10000/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Get Homes
GET http://localhost:10000/homes HTTP/1.1

### Get Home by id

GET http://localhost:10000/homes/63320f8a91a6228434acc521 HTTP/1.1




// render



### Create Realtor
POST https://realtorzone.onrender.com/realtors HTTP/1.1
Content-Type: application/json

{
  "firstName": "Blake",
  "lastName": "King",
  "email": "BlakeKing@fakemail.com",
  "phone": "555-555-5555",
  "city": "New York",
  "state": "NY",
  "zip": "10001"
}

### Edit Realtor
PUT https://realtorzone.onrender.com/realtors/63320f8a91a6228434acc521 HTTP/1.1 
content-type: application/json

{
  "firstName": "Blake",
  "lastName": "King",
  "email": "BlakeKing@fakemail.com",
  "phone": "111-111-1111",
  "city": "New York",
  "state": "NY",
  "zip": "10001"

}
### Delete Realtor
DELETE https://realtorzone.onrender.com/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Get Realtors
GET https://realtorzone.onrender.com/realtors HTTP/1.1

### Get Realtor by id

GET https://realtorzone.onrender.com/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Create Home
POST https://realtorzone.onrender.com/homes HTTP/1.1
Content-Type: application/json

{
     "sellerFirstName" : "Blake",
      "sellerLastName" : "King",
      "address" : "123 Main St",
      "realtorName": "Blake King",
      "realtorPhone": "555-555-5555",
}

### Edit Home
PUT https://realtorzone.onrender.com/homes HTTP/1.1 
content-type: application/json

{
     "sellerFirstName" : "Joe",
      "sellerLastName" : "King",
      "address" : "123 Main St",
      "realtorName": "Blake King",
      "realtorPhone": "555-555-5555",

}
### Delete Home
DELETE https://realtorzone.onrender.com/realtors/63320f8a91a6228434acc521 HTTP/1.1

### Get Homes
GET https://realtorzone.onrender.com/homes HTTP/1.1

### Get Home by id

GET https://realtorzone.onrender.com/homes/63320f8a91a6228434acc521 HTTP/1.1

### Get api documentation
GET realtorzone.onrender.com/api-docs HTTP/1.1



